{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}-ingress
  annotations:
    kubernetes.io/elb.port: {{ .Values.ingress.port | quote }}
    {{- if .Values.ingress.elb.autocreate }}
    kubernetes.io/elb.class: union
    kubernetes.io/elb.autocreate:
      '{
          "name":"{{ .Values.name }}-elb",
          "type":"public",
          "bandwidth_name":"codbex-helios-bandwidth",
          "bandwidth_chargemode":"traffic",
          "bandwidth_size":5,
          "bandwidth_sharetype":"PER",
          "eip_type":"5_bgp"
        }'
    {{- end }}
    {{- if not .Values.ingress.elb.autocreate }}
    kubernetes.io/elb.id: {{ .Values.ingress.elb.existing.id }} # Load balancer ID
    kubernetes.io/elb.class: {{ .Values.ingress.elb.existing.class }}   # Load balancer type
    {{- end }}
spec:
  rules:
    - host: ''
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              service:
                name: {{ .Values.name }}-svc
                port:
                  number: {{ .Values.service.ports.http }}
            pathType: Prefix
#            property:
#              ingress.beta.kubernetes.io/url-match-mode: STARTS_WITH
#            pathType: ImplementationSpecific # Prefix
  ingressClassName: cce    # OTC LoadBalancer is used.
{{- end }}
