name: Build - Platform

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: codbex/codbex-infra/.github/workflows/platform-build.yaml@main
    with:
      platform-name: codbex-helios
      docker-build: true
      release-otc-helm-chart: true
    secrets: inherit
