name: Build - Platform

on:
  push:
    branches:
      - main

jobs:
  main:
    uses: codbex/codbex-infra/.github/workflows/platform-build.yaml@main
    with:
      platform-name: codbex-helios
      docker-build: true
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
