name: Build - Platform

on:
  push:
    branches:
      - main

jobs:
  main:
    uses: codbex/codbex-infra/.github/workflows/platform-build.yaml@main
    secrets: inherit
    with:
      platform-name: codbex-helios
      docker-build: true
      release-otc-helm-chart: true
